SELECT 
    DISTINCT
    CAST (STANDARD_HASH(IDMP.ENTP_PRD_NM || 'ADMINISTERED DRUG PRODUCT PRESENTATION' || IDMP.UOP_DESC || IDMP.CONC_VALUE || B.STD_VALUE) AS VARCHAR2(255)) AS ADMN_PRES_PKEY,
    IDMP.ENTP_PRD_NM,
    IDMP.PRD_NM,
    IDMP.ADMN_PRD_NM AS PIPE_ENTP_PRD_NM,
    'ADMINISTERED DRUG PRODUCT PRESENTATION' AS PRD_CATG,
    IDMP.ENTP_PRD_DESC,
    REPLACE(IDMP.DS_STR, '.0', '') AS DS_STR,
    NVL(IDMP.DS_STR_UOM, 'N/A') AS DS_STR_UOM,
    NVL(A.STD_VALUE, 'N/A') AS STD_DS_STR_UOM,
    IDMP.ADMN_DS_FRM_CD,
    IDMP.ADMN_DS_FRM_CD_DESC,
    IDMP.UOP,
    IDMP.UOP_DESC,
    CASE 
        WHEN IDMP.C_N1 IS NOT NULL AND IDMP.C_N1 <> 'N/A' AND IDMP.C_N2 IS NOT NULL AND IDMP.C_N2 <> 'N/A' THEN UPPER(TRIM(IDMP.C_N1 || '/' || IDMP.C_N2)) 
        ELSE IDMP.C_N1 
    END AS CONC_VALUE,
    CASE 
        WHEN IDMP.C_D1 IS NOT NULL AND IDMP.C_D1 <> 'N/A' AND IDMP.C_D2 IS NOT NULL AND IDMP.C_D2 <> 'N/A' THEN UPPER(TRIM(IDMP.C_D1 || '/' || IDMP.C_D2)) 
        ELSE IDMP.C_N2 
    END AS CONC_UOM,
    EDF.PIPELINE_CANDIDATE_KEY,
    IDMP.ROWID_OBJECT,
    IDMP.ADMN_RTE_CD,
    IDMP.ADMN_RTE_CD_DESC,
    IDMP.LG_CD,
    IDMP.PHM_PRD_DESC AS ADMN_PRD_DESC
FROM
    IDMP_VIEW IDMP
LEFT JOIN
    (SELECT 
         DISTINCT ENTP_PRD_NM, UPPER(TRD_NM.TRADE_NM) AS TRADE_NM 
     FROM C_BO_ENT_PRD ENT_PRD 
     INNER JOIN C_BO_TRD_NM TRD_NM ON ENT_PRD.ROWID_OBJECT = TRD_NM.ENTP_PRD_FK) TRD_NM ON IDMP.BRAND = TRD_NM.TRADE_NM
LEFT JOIN
    (SELECT * FROM C_L_CONFIG_STD_VALUE WHERE TYP = 'UNIT') A ON IDMP.DS_STR_UOM = A.RAW_VALUE
LEFT JOIN
    (SELECT * FROM C_L_CONFIG_STD_VALUE WHERE TYP = 'UNIT') B ON IDMP.CONC_UOM = B.RAW_VALUE
LEFT JOIN
    (SELECT 
         EDF_PIPELINE_CANDIDATE_KEY
     FROM SOME_OTHER_TABLE) EDF ON IDMP.SOME_JOIN_CONDITION = EDF.SOME_JOIN_CONDITION;
